version: "3.8"
services:
  scanner:
    image: ghcr.io/briandorantes1995/clamavscanner:latest
    container_name: scanner
    restart: always
    depends_on:
      - clamd
    networks:
      - internal
    healthcheck:
      test: [ "CMD","bash","-c","echo PING | nc localhost 3310" ]
      interval: 30s
      timeout: 10s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - scanner
    networks:
      - internal
      
  freshclam:
    image: clamav/clamav:stable
    container_name: freshclam
    restart: unless-stopped
    command: ["/init-unprivileged"]
    environment:
      - CLAMAV_NO_CLAMD=true
    volumes:
      - clamdb:/var/lib/clamav
    networks:
      - internal

  clamd:
    image: clamav/clamav:stable
    container_name: clamd
    restart: unless-stopped
    depends_on:
      - freshclam
    volumes:
      - clamdb:/var/lib/clamav
      - scans:/scans
    networks:
      - internal

volumes:
  clamdb:
  scans:
  caddy_data:
  caddy_config:
    
networks:
   internal:  
    
    